name: Daily Stock Analysis

on:
  schedule:
    # 运行在每个交易日的 08:30 (UTC), 对应中国时间 16:30
    - cron: '30 8 * * 1-5'
  workflow_dispatch: # 允许手动触发

jobs:
  stock-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run stock analysis
      run: |
        python3 analysis/optimized_stock_analyzer.py
        
    - name: Deploy to Railway
      if: success()
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        # 部署到Railway (如果需要的话)
        echo "Analysis completed successfully"
        
    - name: Commit updated data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --staged --quiet || git commit -m "Update stock analysis data [$(date +'%Y-%m-%d %H:%M:%S')]"
        git push || echo "No changes to push"